version: "3.7"

services:
  postgreDB:
    image: postgres
    container_name: ticket_foroushi 
    ports:
      - 5434:5432
    volumes:
      - ticket_foroushi:/var/lib/postgresql/data 
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

volumes:
  ticket_foroushi:
    